### ISSUE TITLE
Rewrite the fonts implementation

### ISSUE THREAD

**Issue by Gecko05** [Gecko05/SSD1351-Driver-Library#15]
The current font implementation doesn't allow for fonts wider than 16 px and wastes memory space when fonts are smaller. Need to write a more flexible implementation that saves space when fonts are small and allows for different widths.

**Comment by snail23** [comment]
How do you convert a font to your `font_t.data` format?

**Comment by Gecko05** [comment]
Currently there's no way to do that, it's an enhancement that would be nice to have though. #10 
If a new font is needed, one would need to write an array for each font that has the pixel data needed for each letter, if the font is 7x10, then each letter needs 10 integers of 16 bits and the pixel data should be within the first 7 bits of each integer.

**Comment by snail23** [comment]
I figured it out, should be able to replace the main code in `SSD1351_write_char` with the following in order to use standard fonts.

E.g. replace:
```
      for (int i = 0; i < font.height; i++){
        fd = font.data[(c - 32) * font.height + i];
        for (int j = 0; j < font.width; j++){
          if ((fd << j) & 0x8000){
            SSD1351_write_pixel(SSD1351_cursor.x + j, SSD1351_cursor.y + i, color);
          }
        }
      }
```
With:
```
        for (int i = 0; i < font.height; i++)
        {
            fd = font.data[(c - font.first) * font.height + i];
            for (int j = 0; j < font.width; j++)
            {
                if ((fd << j) & 0x80)
                    SSD1351_write_pixel(SSD1351_cursor.x + j, SSD1351_cursor.y + i, color);
            }
        }
```
`font_t` now looks like this:
```
typedef struct {
	uint8_t width;    // Font width in pixels
	uint8_t height;   // Font height in pixels
        uint8_t first;    // first glyph supported, 32 for ' '
	uint16_t *data; // Pointer to data font data array
} font_t;
```
The font I am using with this is the IBM VGA 8x14 font.
https://github.com/spacerace/romfont/blob/master/font-headers/IBM_VGA_8x14.h

Maybe this will help someone down the line. Great library!

**Comment by Gecko05** [comment]
Ohh thanks, will add this to the library!

**Comment by Gecko05** [comment]
Added support for 8 bit fonts, can now use IBM_VGA_8x14.h as shown in **example_with_emulator_WIN**.
